### ISSUE TITLE
Replace `make` and `makefile` with Grunt or Gulp

### ISSUE THREAD

**Issue by netmilk** [leboncoin/morphlingjs#13]
I'd suggest using one of the Node.js ecosystem native task runners instead of the hardcore unix `make` in order to make the codebase more contribution friendly.

Even if not using the JS API of the build components (Babel) and just using the CLI I'd suggest using for instance [`grunt-exec`](https://www.npmjs.com/package/grunt-exec)

**Comment by vroudge** [comment]
Hi @netmilk and thank you very much for your multiple contributions!

It would probably be a better idea to move all the `make` scripts directly to the `package.json`.

Would you be willing to submit a PR on this?
