### ISSUE TITLE
"Not Found" response when adding my own swagger

### ISSUE THREAD

**Issue by enna** [leboncoin/morphlingjs#2]
Hello,

I installed morphling globally and tested it with supplied example swaggers, everything works fine. :)
Then I added my own swagger and now I get a "Not Found" on every URL that worked before (except for overrided pattern which still works very well). There wasn't any error while applying my new swagger.

NB : if you need my own swagger file I can send it to you via email (because it's quite confidential). ;)

Thanks in advance.

**Comment by vroudge** [comment]
Hello Enna,

It seems to me, as I've seen your swagger, that *you include JSON in the swagger which is in a YAML format*.

That wouldn't work. Either you can use a YAML file in a YAML format, or a JSON file in JSON format.

Also, refrain from using newline characters in your strings. Parsers will see a newline and break 👍 .

Pushing something right now to fix your issues.
